# Tell Travis (travisci.org) what to do

language: python

python:
  - 2.5
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - pypy

install:
  - python setup.py clean install
  - python igor.py zip_mods install_egg remove_extension

script:
  - python igor.py test_with_tracer py
  - python igor.py test_with_tracer c
